src/Entity/Produits.php
<?php

namespace App\Entity;

use App\Repository\ProduitsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitsRepository::class)
 */
class Produits
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pdt_libelle;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_At;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Updated_At;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $pdt_reference;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pdt_description;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $pdt_image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pdt_descint;

    /**
     * @ORM\ManyToMany(targetEntity=UniteMesure::class, inversedBy="pdt_id")
     */
    private $um;

    /**
     * @ORM\ManyToOne(targetEntity=EtatProduit::class, inversedBy="pdt_id")
     */
    private $etp;

    /**
     * @ORM\ManyToOne(targetEntity=GammeProduit::class, inversedBy="pdt_id")
     */
    private $gamme;

    /**
     * @ORM\ManyToOne(targetEntity=MarqueProduit::class, inversedBy="pdt_id")
     */
    private $marque;

    /**
     * @ORM\ManyToOne(targetEntity=TypeProduit::class, inversedBy="produit")
     */
    private $tpd;

    /**
     * @ORM\OneToMany(targetEntity=ProduitExtension::class, mappedBy="produit")
     */
    private $produit;



    public function __construct()
    {
        $this->um_id = new ArrayCollection();
        $this->produit = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getPdtLibelle()
    {
        return $this->pdt_libelle;
    }

    /**
     * @param mixed $pdt_libelle
     */
    public function setPdtLibelle($pdt_libelle): void
    {
        $this->pdt_libelle = $pdt_libelle;
    }

    /**
     * @return mixed
     */
    public function getPdtDescint()
    {
        return $this->pdt_descint;
    }

    /**
     * @param mixed $pdt_descint
     */
    public function setPdtDescint($pdt_descint): void
    {
        $this->pdt_descint = $pdt_descint;
    }

    /**
     * @return mixed
     */
    public function getUm()
    {
        return $this->um;
    }

    /**
     * @param mixed $um
     */
    public function setUm($um): void
    {
        $this->um = $um;
    }

    /**
     * @return mixed
     */
    public function getEtp()
    {
        return $this->etp;
    }

    /**
     * @param mixed $etp
     */
    public function setEtp($etp): void
    {
        $this->etp = $etp;
    }

    /**
     * @return mixed
     */
    public function getGamme()
    {
        return $this->gamme;
    }

    /**
     * @param mixed $gamme
     */
    public function setGamme($gamme): void
    {
        $this->gamme = $gamme;
    }

    /**
     * @return mixed
     */
    public function getMarque()
    {
        return $this->marque;
    }

    /**
     * @param mixed $marque
     */
    public function setMarque($marque): void
    {
        $this->marque = $marque;
    }

    /**
     * @return mixed
     */
    public function getTpd()
    {
        return $this->tpd;
    }

    /**
     * @param mixed $tpd
     */
    public function setTpd($tpd): void
    {
        $this->tpd = $tpd;
    }


    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_At;
    }

    public function setCreatedAt(\DateTimeInterface $created_At): self
    {
        $this->created_At = $created_At;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->Updated_At;
    }

    public function setUpdatedAt(\DateTimeInterface $Updated_At): self
    {
        $this->Updated_At = $Updated_At;

        return $this;
    }

    public function getPdtReference(): ?string
    {
        return $this->pdt_reference;
    }

    public function setPdtReference(string $pdt_reference): self
    {
        $this->pdt_reference = $pdt_reference;

        return $this;
    }

    public function getPdtDescription(): ?string
    {
        return $this->pdt_description;
    }

    public function setPdtDescription(?string $pdt_description): self
    {
        $this->pdt_description = $pdt_description;

        return $this;
    }

    public function getPdtImage(): ?string
    {
        return $this->pdt_image;
    }

    public function setPdtImage(?string $pdt_image): self
    {
        $this->pdt_image = $pdt_image;

        return $this;
    }



    /**
     * @return Collection|UniteMesure[]
     */
    public function getUmId(): Collection
    {
        return $this->um_id;
    }

    public function addUmId(UniteMesure $umId): self
    {
        if (!$this->um_id->contains($umId)) {
            $this->um_id[] = $umId;
        }

        return $this;
    }

    public function removeUmId(UniteMesure $umId): self
    {
        if ($this->um_id->contains($umId)) {
            $this->um_id->removeElement($umId);
        }

        return $this;
    }

    /**
     * @return Collection|ProduitExtension[]
     */
    public function getProduit(): Collection
    {
        return $this->produit;
    }

    public function addProduit(ProduitExtension $produit): self
    {
        if (!$this->produit->contains($produit)) {
            $this->produit[] = $produit;
            $produit->setProduit($this);
        }

        return $this;
    }

    public function removeProduit(ProduitExtension $produit): self
    {
        if ($this->produit->contains($produit)) {
            $this->produit->removeElement($produit);
            // set the owning side to null (unless already changed)
            if ($produit->getProduit() === $this) {
                $produit->setProduit(null);
            }
        }

        return $this;
    }


    public function __toString(){
        // to show the name of the Category in the select
        return $this->pdt_libelle;
        // to show the id of the Category in the select
        // return $this->id;
    }




}

src/Form/ProduitsType.php
<?php

namespace App\Form;

use App\Entity\Produits;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pdt_libelle')
            ->add('pdt_reference')
            ->add('pdt_description')
            ->add('pdt_image')
            ->add('pdt_desc_int')
            ->add('um')
            ->add('etp')
            ->add('gamme')
            ->add('marque')
            ->add('tpd')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produits::class,
        ]);
    }
}

src/Controller/ProduitsController.php
<?php

namespace App\Controller;

use App\Entity\Produits;
use App\Form\ProduitsType;
use App\Repository\ProduitsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/produits")
 */
class ProduitsController extends AbstractController
{
    /**
     * @Route("/", name="produits_index", methods={"GET"})
     */
    public function index(ProduitsRepository $produitsRepository): Response
    {
        return $this->render('produits/index.html.twig', [
            'produits' => $produitsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/", name="dashboard", methods={"GET"})

    public function dashboard(ProduitsRepository $produitsRepository): Response
    {
        return $this->render('dashboard/dashboard.html.twig', [
            'produit' => $produitsRepository->findAll(),
        ]);
    }
     * */

    /**
     * @Route("/new", name="produits_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $produit = new Produits();
        $form = $this->createForm(ProduitsType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $produit->setCreatedAt(new \DateTime())
                ->setUpdatedAt(new \DateTime());
            $entityManager->persist($produit);
            $entityManager->flush();
            return $this->redirectToRoute('produits_index');
        }

        return $this->render('produits/new.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="produits_show", methods={"GET"})
     */
    public function show(Produits $produit): Response
    {
        return $this->render('produits/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="produits_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Produits $produit): Response
    {
        $form = $this->createForm(ProduitsType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('produits_index');
        }

        return $this->render('produits/edit.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="produits_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Produits $produit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('produits_index');
    }
}

templates/produits/_delete_form.html.twig
<form method="post" action="{{ path('produits_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn btn-danger btn-simple"><i class="material-icons">delete_sweep</i></button>
</form>

templates/produits/_form.html.twig
{{ form_start(form) }}
<div class="form-row">
    <div class="form-group col-md-6" >
        <label for="" class="bmd-label-floating">Nom Produit</label>
        {{ form_row(form.pdt_libelle, {'label': false, 'attr' : {'class': 'form-control'}}) }}
    </div>
    <div class="form-group col-md-6  ">
        <label for="" class="bmd-label-floating">Référence Produit</label>
        {{ form_row(form.pdt_reference, { 'label': false, 'attr' : {'class': 'form-control'}}) }}
    </div>
    <div class="form-group col-md-6">
        <label for="" class="bmd-label-floating">Description Produit</label>
        {{ form_row(form.pdt_description, { 'label': false, 'attr' : {'class': 'form-control'}}) }}
    </div>
    <div class="form-group col-md-6  ">
        <label for="" class="bmd-label-floating">Description Int Produit</label>
        {{ form_row(form.pdt_desc_int, { 'label': false, 'attr' : {'class': 'form-control'}}) }}
    </div>
    <div class="form-group col-md-6">
        <label for="" class="bmd-label-floating">Image Produit</label>
        {{ form_row(form.pdt_image, { 'label': false, 'attr' : {'class': 'form-control'}}) }}
    </div>
    <div class="form-group col-md-6">
        <label for="" class="bmd-label-floating">Unité Mesure</label>
        {{ form_row(form.um, { 'label': false, 'attr' : {'class': 'form-control','style':'height:100px'}}) }}
    </div>
    <div class="form-group col-md-6">
        <label for="" class="bmd-label-floating">Etat Produit</label>
        {{ form_row(form.etp, { 'label': false, 'attr' : {'class': 'form-control mdb-select colorful-select dropdown-primary'}, 'data-style': "btn btn-link"}) }}
    </div>
    <div class="form-group col-md-6">
        <label for="" class="bmd-label-floating">Gamme Produit</label>
        {{ form_row(form.gamme, {'label': false,  'attr' : {'class': 'form-control'}, 'data-style': "btn btn-link"}) }}
    </div>
    <div class="form-group col-md-6">
        <label for="" class="bmd-label-floating">Type Produit</label>
        {{ form_row(form.tpd, {'label': false,  'attr' : {'class': 'form-control'}, 'data-style': "btn btn-link"}) }}
    </div>
    <div class="form-group col-md-6">
        <label for="" class="bmd-label-floating">Marque Produit</label>
        {{ form_row(form.marque, {'label': false,  'attr' : {'class': 'form-control'}, 'data-style': "btn btn-link"}) }}
    </div>
    <div class="form-group col-md-6 text-left">
        <a class="btn btn-dark"  href="{{ path('produits_index') }}"><i class="fa fa-arrow-left mr-2" aria-hidden="true"></i> back to list</a>
    </div>
    <div class="form-group col-md-6 text-right">
        <button class="btn btn-success ">{{ button_label|default('Ajouter') }}</button>
    </div>
</div>
{{ form_end(form) }}

templates/produits/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Produit{% endblock %}

{% block body %}
    <div class="container-fluid" >
        <div class="row">
            <div class="col-md-10 mx-auto">
                <div class="card">
                    <div class="card-header p-0">
                        <div class="alert alert-info">
                            <span>Modifier un Produit</span>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="form-group container">
                            {{ include('produits/_form.html.twig', {'button_label': 'Update'}) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/produits/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produits index{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-xs-12">
                <div class="card">
                    <div class="card-header separator">
                        <h5 class="font-weight-bold">Produits</h5>
                    </div>
                    <div class="card-body">
                        <table class="dataTable table table-striped table-hover">
                            <a class="btn btn-info rounded float-right mb-4 " href="{{ path('produits_new') }}">Ajouter Produit</a>
                            <thead class="current">
                            <tr>
                                <th>Réference</th>
                                <th>Désignation</th>
                                <th>Description</th>
                                <th>Description interne</th>
                                <th>Marque</th>
                                <th class="text-right">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for produit in produits %}
                                <tr >
                                    <td>{{ produit.pdtReference }}</td>
                                    <td>{{ produit.pdtLibelle }}</td>
                                    <td>{{ produit.pdtDescription }}</td>
                                    <td>{{ produit.pdtDescint }}</td>
                                    <td>{{ produit.marque }}</td>
                                <td class="td-actions text-right">
                                    <a class="btn btn-warning btn-simple" href="{{ path('produits_show', {'id': produit.id}) }}"><i class="material-icons">remove_red_eye</i></a>
                                    <a class="btn btn-warning btn-simple" href="{{ path('produits_edit', {'id': produit.id}) }}"><i class="material-icons">edit</i></a>
                                    {{ include('produits/_delete_form.html.twig') }}
                                </td>
</tr>
{% else %}
<tr>
<td colspan="8" class="text-center">no records found</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

templates/produits/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un Produit{% endblock %}

{% block body %}
    <div class="container-fluid" >
        <div class="row">
            <div class="col-md-10 mx-auto">
                    <div class="card">
                        <div class="card-header p-0">
                            <div class="alert alert-info">
                                <span>Ajouter un Produit</span>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="form-group container">
                                {{ include('produits/_form.html.twig') }}
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/produits/produits.html.twig
{% extends 'base.html.twig' %}

{% block title 'Produits' %}

{% block body %}
<!-- ============================================================== -->
<!-- Page Content -->
<!-- ============================================================== -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row bg-title">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Dashboard</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <!-- <a href="https://wrappixel.com/templates/ampleadmin/" target="_blank"
                            class="btn btn-danger pull-right m-l-20 hidden-xs hidden-sm waves-effect waves-light">Upgrade
                            to Pro</a> -->
                <ol class="breadcrumb">
                    <li><a href="#">Dashboard</a></li>
                </ol>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- ============================================================== -->
        <!-- table -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-md-12 col-lg-12 col-sm-12">
                <div class="white-box">
                    <div class="col-md-3 col-sm-4 col-xs-6 pull-right">
                        <select class="form-control pull-right row b-none">
                            <option>March 2017</option>
                            <option>April 2017</option>
                            <option>May 2017</option>
                            <option>June 2017</option>
                            <option>July 2017</option>
                        </select>
                    </div>
                    <h3 class="box-title">Liste des produits</h3>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Libelle</th>
                                    <th>Catégorie</th>
                                    <th>DATE Achat</th>
                                    <th>Marque</th>
                                    <th colspan="3">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td class="txt-oflo">HP Elitebook</td>
                                    <td class="txt-oflo">PROD_HXJ</td>
                                    <td>Ordinateurs</td>
                                    <td><span class="text-info">HP</span></td>
                                    <td><button class="btn btn-info"><i class="fa fa-edit"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-danger"><i class="fa fa-trash-o"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-success"><i class="fa fa-eye"
                                                aria-hidden="true"></i></button></td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td class="txt-oflo">Renault CLIO</td>
                                    <td class="txt-oflo">PROD_MKL12</td>
                                    <td>Automobile</td>
                                    <td><span class="text-info">Renault</span></td>
                                    <td><button class="btn btn-info"><i class="fa fa-edit"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-danger"><i class="fa fa-trash-o"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-success"><i class="fa fa-eye"
                                                aria-hidden="true"></i></button></td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td class="txt-oflo">Peugeot CLIO</td>
                                    <td class="txt-oflo">PROD_AMD903</td>
                                    <td>Automobile</td>
                                    <td><span class="text-info">Peugeot</span></td>
                                    <td><button class="btn btn-info"><i class="fa fa-edit"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-danger"><i class="fa fa-trash-o"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-success"><i class="fa fa-eye"
                                                aria-hidden="true"></i></button></td>
                                </tr>

                                <tr>
                                    <td>4</td>
                                    <td class="txt-oflo">Peugeot CLIO</td>
                                    <td class="txt-oflo">PROD_XY672</td>
                                    <td>Automobile</td>
                                    <td><span class="text-info">Peugeot</span></td>
                                    <td><button class="btn btn-info"><i class="fa fa-edit"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-danger"><i class="fa fa-trash-o"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-success"><i class="fa fa-eye"
                                                aria-hidden="true"></i></button></td>
                                </tr>
                                <tr>
                                    <td>5</td>
                                    <td class="txt-oflo">Aygo</td>
                                    <td class="txt-oflo">PROD_EF728</td>
                                    <td>Automobile</td>
                                    <td><span class="text-info">Toyota</span></td>
                                    <td><button class="btn btn-info"><i class="fa fa-edit"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-danger"><i class="fa fa-trash-o"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-success"><i class="fa fa-eye"
                                                aria-hidden="true"></i></button></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- chat-listing & recent comments -->
        <!-- ============================================================== -->
        <div class="row">
        </div>
    </div>
    <!-- /.container-fluid -->

</div>
<!-- ============================================================== -->
<!-- End Page Content -->

{% endblock %}

templates/produits/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produits{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 mx-auto">
                    <div class="card">
                        <div class="card-header p-0">
                            <div class="alert alert-info">
                                <span>Détail du Produit {{ produit.id }}</span>
                            </div>
                        </div>
                        <div class="card-body">
                           <div class="float-right"> {{ include('produits/_delete_form.html.twig') }}</div>
                            <ul class="nav nav-pills nav-pills-primary" role="tablist">
                                <li class="nav-item mr-3"><a class="nav-link btn btn-outline-primary  active" href="#tab1" data-toggle="tab" aria-expanded="true">Produit</a></li>
                                <li class="nav-item mr-3"><a class="nav-link btn btn-outline-primary " href="#tab2" data-toggle="tab" aria-expanded="false">Type</a></li>
                                <li class="nav-item mr-3"><a class="nav-link btn btn-outline-primary " href="#tab3" data-toggle="tab" aria-expanded="false">Marque</a></li>
                                <li class="nav-item mr-3"><a class="nav-link btn btn-outline-primary " href="#tab4" data-toggle="tab" aria-expanded="false">Gamme</a></li>
                            </ul>
                            <div class="tab-content tab-space ">
                                <div class="tab-pane active" id="tab1" aria-expanded="true">
                                    <div class="form-group ">
                                        <table class="table table-shopping">
                                            <tbody>
                                            <tr>
                                                <td>Libelle</td>
                                                <td> {{ produit.getPdtLibelle() }}</td>
                                            </tr>
                                            <tr>
                                                <td>Réference</td>
                                                <td>{{ produit.getPdtReference() }}</td>
                                            </tr>
                                            <tr>
                                                <td>CreatedAt</td>
                                                <td>{{ produit.createdAt ? produit.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                                            </tr>
                                            <tr>
                                                <td>UpdatedAt</td>
                                                <td>{{ produit.updatedAt ? produit.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                                            </tr>
                                            <tr>
                                                <td>Description</td>
                                                <td>{{ produit.PdtDescription() }}</td>
                                            </tr>
                                            <tr>
                                                <td>Description Interne</td>
                                                <td> {{ produit.getPdtLibelle() }}</td>
                                            </tr>
                                            <tr>
                                                <td>Image</td>
                                                <td>{{ produit.getPdtImage() }}</td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <div class="form-group">
                                            <a class="float-left" href="{{ path('produits_index') }}">
                                                <button class="btn btn-outline-dark"><i class="material-icons">reply</i></button></a>
                                            <a class="float-right" href="{{ path('produits_edit', {'id': produit.id}) }}">
                                                <button class="btn btn-outline-warning"><i class="material-icons">edit</i></button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane" id="tab2" aria-expanded="false">Vous pouvez consulter le détail sur le public</div>
                                <div class="tab-pane" id="tab3" aria-expanded="false">Vous pouvez consulter le détail des objectifs pédagogiques</div>
                                <div class="tab-pane" id="tab4" aria-expanded="false">Vous pouvez consulter le détail des compléments</div>
                            </div>
                        </div>
                    </div>
            </div>
         </div>
    </div>
{% endblock %}