src/Entity/Parametres.php
<?php

namespace App\Entity;

use App\Repository\ParametresRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ParametresRepository::class)
 */
class Parametres
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $par_parametre;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $par_valeur;

    /**
     * @ORM\OneToMany(targetEntity=ProduitExtension::class, mappedBy="parametres")
     */
    private $param;

    public function __construct()
    {
        $this->param = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getParParametre(): ?string
    {
        return $this->par_parametre;
    }

    public function setParParametre(string $par_parametre): self
    {
        $this->par_parametre = $par_parametre;

        return $this;
    }

    public function getParValeur(): ?string
    {
        return $this->par_valeur;
    }

    public function setParValeur(string $par_valeur): self
    {
        $this->par_valeur = $par_valeur;

        return $this;
    }

    /**
     * @return Collection|ProduitExtension[]
     */
    public function getParam(): Collection
    {
        return $this->param;
    }

    public function addParam(ProduitExtension $param): self
    {
        if (!$this->param->contains($param)) {
            $this->param[] = $param;
            $param->setParametres($this);
        }

        return $this;
    }

    public function removeParam(ProduitExtension $param): self
    {
        if ($this->param->contains($param)) {
            $this->param->removeElement($param);
            // set the owning side to null (unless already changed)
            if ($param->getParametres() === $this) {
                $param->setParametres(null);
            }
        }

        return $this;
    }
}

src/Form/ParametresType.php
<?php

namespace App\Form;

use App\Entity\Parametres;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ParametresType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('par_parametre')
            ->add('par_valeur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Parametres::class,
        ]);
    }
}

src/Controller/ParametresController.php
<?php

namespace App\Controller;

use App\Entity\Parametres;
use App\Form\ParametresType;
use App\Repository\ParametresRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/parametres")
 */
class ParametresController extends AbstractController
{
    /**
     * @Route("/", name="parametres_index", methods={"GET"})
     */
    public function index(ParametresRepository $parametresRepository): Response
    {
        return $this->render('parametres/index.html.twig', [
            'parametres' => $parametresRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="parametres_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $parametre = new Parametres();
        $form = $this->createForm(ParametresType::class, $parametre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($parametre);
            $entityManager->flush();

            return $this->redirectToRoute('parametres_index');
        }

        return $this->render('parametres/new.html.twig', [
            'parametre' => $parametre,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="parametres_show", methods={"GET"})
     */
    public function show(Parametres $parametre): Response
    {
        return $this->render('parametres/show.html.twig', [
            'parametre' => $parametre,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="parametres_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Parametres $parametre): Response
    {
        $form = $this->createForm(ParametresType::class, $parametre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('parametres_index');
        }

        return $this->render('parametres/edit.html.twig', [
            'parametre' => $parametre,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="parametres_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Parametres $parametre): Response
    {
        if ($this->isCsrfTokenValid('delete'.$parametre->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($parametre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('parametres_index');
    }
}

templates/parametres/_delete_form.html.twig
<form method="post" action="{{ path('parametres_delete', {'id': parametre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ parametre.id) }}">
    <button class="btn btn-sm btn-outline-danger">Delete</button>
</form>

templates/parametres/_form.html.twig
{{ form_start(form) }}
<div class="form-group">
    <label for="" class="bmd-label-floating">Libelle Paramétre</label>
    {{ form_row(form.par_parametre, {'label': false, 'attr' : {'class': 'form-control'}}) }}
</div>
<div class="form-group">
    <label for="" class="bmd-label-floating">Valeur Paramétre</label>
    {{ form_row(form.par_valeur, {'label': false, 'attr' : {'class': 'form-control'}}) }}
</div>
<button class="btn btn-success btn-block">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/parametres/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Parametres{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <div class="card shadow-normal radius">
                    <div class="card-header card-header-primary b-2">
                        <h2 class="text-center">MODIFIER UN PARAMETRE</h2>
                    </div>
                    <div class="container">
                        <div class="card-body">
                            {{ include('parametres/_form.html.twig', {'button_label': 'Update'}) }}
                        </div>
                        <div class="card-footer p-3">
                            {{ include('parametres/_delete_form.html.twig') }}
                            <a class="h4" href="{{ path('parametres_index') }}"><i class="fa fa-arrow-left mr-2" aria-hidden="true"></i> back to list</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/parametres/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Parametres index{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-xs-12">
            <div class="card">
                <div class="card-category text-center">
                    <h2>Parametres index</h2></div>
                <div class="card-body">
                    <table class="dataTable table table-striped">
                        <a class="btn btn-info rounded float-right mb-4 " href="{{ path('parametres_new') }}">Ajouter Paramètre</a>
        <thead>
            <tr class="head">
                <th>Id</th>
                <th>Par_parametre</th>
                <th>Par_valeur</th>
                <th style="width: 15%;">actions</th>
            </tr>
        </thead>
        <tbody>
        {% for parametre in parametres %}
            <tr>
                <td>{{ parametre.id }}</td>
                <td>{{ parametre.parParametre }}</td>
                <td>{{ parametre.parValeur }}</td>
                <td>
                    <a class="btn btn-warning btn-sm rounded-circle" href="{{ path('parametres_show', {'id': parametre.id}) }}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                    <a class="btn btn-warning btn-sm rounded-circle" href="{{ path('parametres_edit', {'id': parametre.id}) }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                    <a class="btn btn-danger btn-sm rounded-circle" href="{{ path('parametres_delete', {'id': parametre.id}) }}"><i class="fa fa-trash" aria-hidden="true"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4" class="text-center">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/parametres/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter Paramètres{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <div class="card shadow-normal radius">
                    <div class="card-header card-header-primary b-2">
                        <h2 class="text-center">AJOUTER UN PARAMETRE</h2>
                    </div>
                    <div class="container">
                        <div class="card-body">
                            {{ include('parametres/_form.html.twig') }}
                        </div>
                        <div class="card-footer p-3">
                            <a class="h4" href="{{ path('parametres_index') }}"><i class="fa fa-arrow-left mr-2" aria-hidden="true"></i> back to list</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/parametres/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail des Parametres{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <div class="card shadow-normal radius">
                    <div class="card-header card-header-primary b-2">
                        <h2>Détail du Paramètre {{ parametre.id }}</h2>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="formGroupExampleInput">Id</label>
                            <label type="text" class="form-control" id="formGroupExampleInput">
                                {{ parametre.id }}
                            </label>
                        </div>
                    <div class="form-group">
                    <label for="formGroupExampleInput">Paramètre</label>
                    <label type="text" class="form-control" id="formGroupExampleInput">
                        {{ parametre.parParametre }}
                    </label>
                    </div>
                        <div class="form-group">
                            <label for="formGroupExampleInpu2t">Valeur</label>
                            <label type="text" class="form-control" id="formGroupExampleInput2">
                                {{ parametre.parValeur }}
                            </label>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{{ path('parametres_index') }}">
                            <button class="btn btn-sm btn-outline-warning"><i class="fa fa-arrow-left mr-2" aria-hidden="true"></i>  &nbsp; Revenir au Liste</button></a>
                        <a href="{{ path('parametres_edit', {'id': parametre.id}) }}">
                            <button class="btn btn-sm btn-outline-warning"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>  &nbsp; edit</button>
                        </a>
                        {{ include('parametres/_delete_form.html.twig') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}