src/Entity/TypeProduit.php
<?php

namespace App\Entity;

use App\Repository\TypeProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TypeProduitRepository::class)
 */
class TypeProduit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tpd_libelle;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Produits::class, mappedBy="tpd")
     */
    private $produit;

    public function __construct()
    {
        $this->produit = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTpdLibelle(): ?string
    {
        return $this->tpd_libelle;
    }

    public function setTpdLibelle(string $tpd_libelle): self
    {
        $this->tpd_libelle = $tpd_libelle;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|Produits[]
     */
    public function getProduit(): Collection
    {
        return $this->produit;
    }

    public function addProduit(Produits $produit): self
    {
        if (!$this->produit->contains($produit)) {
            $this->produit[] = $produit;
            $produit->setTpd($this);
        }

        return $this;
    }

    public function removeProduit(Produits $produit): self
    {
        if ($this->produit->contains($produit)) {
            $this->produit->removeElement($produit);
            // set the owning side to null (unless already changed)
            if ($produit->getTpd() === $this) {
                $produit->setTpd(null);
            }
        }

        return $this;
    }

    public function __toString(){
        // to show the name of the Category in the select
        return $this->tpd_libelle;
        // to show the id of the Category in the select
        // return $this->id;
    }
}

src/Form/TypeProduitType.php
<?php

namespace App\Form;

use App\Entity\TypeProduit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TypeProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tpd_libelle')
            ->add('createdAt')
            ->add('updatedAt')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TypeProduit::class,
        ]);
    }
}

src/Controller/TypeProduitController.php
<?php

namespace App\Controller;

use App\Entity\TypeProduit;
use App\Form\TypeProduitType;
use App\Repository\TypeProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/type/produit")
 */
class TypeProduitController extends AbstractController
{
    /**
     * @Route("/", name="type_produit_index", methods={"GET"})
     */
    public function index(TypeProduitRepository $typeProduitRepository): Response
    {
        return $this->render('type_produit/index.html.twig', [
            'type_produits' => $typeProduitRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="type_produit_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $typeProduit = new TypeProduit();
        $form = $this->createForm(TypeProduitType::class, $typeProduit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($typeProduit);
            $entityManager->flush();

            return $this->redirectToRoute('type_produit_index');
        }

        return $this->render('type_produit/new.html.twig', [
            'type_produit' => $typeProduit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="type_produit_show", methods={"GET"})
     */
    public function show(TypeProduit $typeProduit): Response
    {
        return $this->render('type_produit/show.html.twig', [
            'type_produit' => $typeProduit,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="type_produit_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, TypeProduit $typeProduit): Response
    {
        $form = $this->createForm(TypeProduitType::class, $typeProduit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('type_produit_index');
        }

        return $this->render('type_produit/edit.html.twig', [
            'type_produit' => $typeProduit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="type_produit_delete", methods={"DELETE"})
     */
    public function delete(Request $request, TypeProduit $typeProduit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$typeProduit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($typeProduit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('type_produit_index');
    }
}

templates/type_produit/_delete_form.html.twig
<form method="post" action="{{ path('type_produit_delete', {'id': type_produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ type_produit.id) }}">
    <button class="btn btn-sm btn-outline-danger">Delete</button>
</form>

templates/type_produit/_form.html.twig
{{ form_start(form) }}
<div class="form-group">
    <label for="" class="bmd-label-floating">Libelle Type</label>
    {{ form_row(form.tpd_libelle, {'label': false, 'attr' : {'class': 'form-control'}}) }}
</div>
<button class="btn btn-success btn-block">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/type_produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Un Type{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <div class="card shadow-normal radius">
                    <div class="card-header card-header-primary b-2">
                        <h2 class="text-center">MODIFIER UN TYPE</h2>
                    </div>
                    <div class="container">
                        <div class="card-body">
                            {{ include('type_produit/_form.html.twig', {'button_label': 'Update'}) }}
                        </div>
                        <div class="card-footer p-3">
                            {{ include('type_produit/_delete_form.html.twig') }}
                            <a class="h4" href="{{ path('type_produit_index') }}"><i class="fa fa-arrow-left mr-2" aria-hidden="true"></i> back to list</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/type_produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}TypeProduit index{% endblock %}

{% block body %}
<<<<<<< HEAD
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-xs-12">
            <div class="card">
                <div class="card-category text-center">
                    <h2>TypeProduit index</h2>
                </div>
                <div class="card-body">
                    <table class="dataTable table table-striped">
                        <a class="btn btn-info rounded float-right mb-4 " href="{{ path('type_produit_new') }}">Ajouter Type</a>
        <thead>
            <tr class="head">
                <th>Tpd_libelle</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th style="width: 15%;">actions</th>
=======
    <h1>TypeProduit index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Tpd_libelle</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th>actions</th>
>>>>>>> a3b9b5db40225ab994d5763f0f2a08e9951242b3
            </tr>
        </thead>
        <tbody>
        {% for type_produit in type_produits %}
            <tr>
<<<<<<< HEAD
                <td>{{ type_produit.getTpdLibelle() }}</td>
                <td>{{ type_produit.createdAt ? type_produit.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ type_produit.updatedAt ? type_produit.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a class="btn btn-warning btn-sm rounded-circle" href="{{ path('type_produit_show', {'id': type_produit.id}) }}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                    <a class="btn btn-warning btn-sm rounded-circle" href="{{ path('type_produit_edit', {'id': type_produit.id}) }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                    <a class="btn btn-danger btn-sm rounded-circle" href="{{ path('type_produit_delete', {'id': type_produit.id}) }}"><i class="fa fa-trash" aria-hidden="true"></i></a>
=======
                <td>{{ type_produit.id }}</td>
                <td>{{ type_produit.tpdLibelle }}</td>
                <td>{{ type_produit.createdAt ? type_produit.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ type_produit.updatedAt ? type_produit.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('type_produit_show', {'id': type_produit.id}) }}">show</a>
                    <a href="{{ path('type_produit_edit', {'id': type_produit.id}) }}">edit</a>
>>>>>>> a3b9b5db40225ab994d5763f0f2a08e9951242b3
                </td>
            </tr>
        {% else %}
            <tr>
<<<<<<< HEAD
                <td colspan="5" class="text-center">no records found</td>
=======
                <td colspan="5">no records found</td>
>>>>>>> a3b9b5db40225ab994d5763f0f2a08e9951242b3
            </tr>
        {% endfor %}
        </tbody>
    </table>
<<<<<<< HEAD
                </div>
            </div>
        </div>
    </div>
</div>
=======

    <a href="{{ path('type_produit_new') }}">Create new</a>
>>>>>>> a3b9b5db40225ab994d5763f0f2a08e9951242b3
{% endblock %}

templates/type_produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter Type Produit{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <div class="card shadow-normal radius">
                    <div class="card-header card-header-primary b-2">
                        <h2 class="text-center">AJOUTER UN TYPE</h2>
                    </div>
                    <div class="container">
                        <div class="card-body">
                            {{ include('type_produit/_form.html.twig') }}
                        </div>
                        <div class="card-footer p-3">
                            <a class="h4" href="{{ path('type_produit_index') }}"><i class="fa fa-arrow-left mr-2" aria-hidden="true"></i> back to list</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/type_produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Type Produit{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <div class="card shadow-normal radius">
                    <div class="card-header card-header-primary b-2">
                        <h2>Détail Type de Produit {{ type_produit.id }}</h2>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="formGroupExampleInput">Id</label>
                            <label type="text" class="form-control" id="formGroupExampleInput">
                                {{ type_produit.id }}
                            </label>
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Libelle</label>
                            <label type="text" class="form-control" id="formGroupExampleInput">
                                {{ type_produit.getTpdLibelle() }}
                            </label>
                        </div>
                        <!--<div class="form-group">
                            <label for="formGroupExampleInput">CreatedAt</label>
                            <label type="text" class="form-control" id="formGroupExampleInput">
                                {{ type_produit.createdAt ? type_produit.createdAt|date('Y-m-d H:i:s') : '' }}
                            </label>
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">UpdatedAt</label>
                            <label type="text" class="form-control" id="formGroupExampleInput">
                                {{ type_produit.updatedAt ? type_produit.updatedAt|date('Y-m-d H:i:s') : '' }}
                            </label>
                        </div>-->
                    </div>
                    <div class="card-footer">
                        <a href="{{ path('type_produit_index') }}">
                            <button class="btn btn-sm btn-outline-warning"><i class="fa fa-arrow-left mr-2" aria-hidden="true"></i>  &nbsp; Revenir au Liste</button></a>
                        <a href="{{ path('type_produit_edit', {'id': type_produit.id}) }}">
                            <button class="btn btn-sm btn-outline-warning"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>  &nbsp; edit</button>
                        </a>
                        {{ include('type_produit/_delete_form.html.twig') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/type_produit/typeProduit.html.twig
{% extends 'base.html.twig' %}

{% block title 'Type des Produits' %}

{% block body %}
<!-- ============================================================== -->
<!-- Page Content -->
<!-- ============================================================== -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row bg-title">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Dashboard</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <!-- <a href="https://wrappixel.com/templates/ampleadmin/" target="_blank"
                            class="btn btn-danger pull-right m-l-20 hidden-xs hidden-sm waves-effect waves-light">Upgrade
                            to Pro</a> -->
                <ol class="breadcrumb">
                    <li><a href="#">Dashboard</a></li>
                </ol>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- ============================================================== -->
        <!-- table -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-md-12 col-lg-12 col-sm-12">
                <div class="white-box">
                    <h3 class="box-title">Types des produits</h3>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Libelle</th>
                                    <th colspan="2" class="text-center resize-actions">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td class="txt-oflo">type1</td>
                                    <td><button class="btn btn-info"><i class="fa fa-edit"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-danger"><i class="fa fa-trash-o"
                                                aria-hidden="true"></i></button></td>

                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td class="txt-oflo">type2</td>
                                    <td><button class="btn btn-info"><i class="fa fa-edit"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-danger"><i class="fa fa-trash-o"
                                                aria-hidden="true"></i></button></td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td class="txt-oflo">type3</td>
                                    <td><button class="btn btn-info"><i class="fa fa-edit"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-danger"><i class="fa fa-trash-o"
                                                aria-hidden="true"></i></button></td>
                                </tr>
                                <tr>
                                    <td>4</td>
                                    <td class="txt-oflo">type4</td>
                                    <td><button class="btn btn-info"><i class="fa fa-edit"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-danger"><i class="fa fa-trash-o"
                                                aria-hidden="true"></i></button></td>
                                </tr>
                                <tr>
                                    <td>5</td>
                                    <td class="txt-oflo">type5</td>
                                    <td><button class="btn btn-info"><i class="fa fa-edit"
                                                aria-hidden="true"></i></button></td>
                                    <td><button class="btn btn-danger"><i class="fa fa-trash-o"
                                                aria-hidden="true"></i></button></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- chat-listing & recent comments -->
        <!-- ============================================================== -->
        <div class="row">
        </div>
    </div>
    <!-- /.container-fluid -->

</div>
<!-- ============================================================== -->
<!-- End Page Content -->

{% endblock %}